model: encoder
checkpoint_path: checkpoints/arcface.ckpt
model_config_path: configs/encoder_arcface/encoder_config_arcface.yaml

dataset:
  root_path: data/fonts
  fonts_test: fonts_test_100.json
  words_test: words_test.json

dataloader:
  batch_size: 128
  num_workers: 8

cluster:
  min_samples: 60
  max_samples: 150
  step: 10

umap:
  n_neighbors: 30
  min_dist: 0.0
  n_components: 32
  random_state: 129
  metric: "cosine"

clustering_method: "AgglomerativeClustering"
clustering_params:
  metric: "cosine"

silhouette_params:
  metric: "cosine"

plot_output_path: "plots/arcface_silhouette.png"
debug: false
