dataset:
  type: "iam_resized"
  root_path: data/iam_resized
  cut: 20000

dataloader:
  batch_size: 128
  num_workers: 8

# Correct number: 117
cluster:
  correct: 117
  min_samples: 50
  max_samples: 180
  step: 10

umap:
  n_neighbors: 120
  min_dist: 0.0
  n_components: 10
  random_state: 42

clustering_method: "KMeans"
clustering_params:
  n_init: 10
  max_iter: 300

silhouette_params:
  metric: "euclidean"

embedding_path: "embeddings/"

plot_output_path: "plots/"
debug: false
