model: encoder
checkpoint_path: checkpoints/cross_entropy.ckpt
model_config_path: configs/encoder_crossentropy/encoder_config_crossentropy.yaml


dataset:
  type: "iam_resized"
  root_path: data/iam_resized

dataloader:
  batch_size: 128
  num_workers: 8
  cut: 20000

# Correct number: 117
cluster:
  correct: 117
  min_samples: 10
  max_samples: 350
  step: 10

umap:
  n_neighbors: 30
  min_dist: 0.0
  n_components: 32
  random_state: 129

clustering_method: "MeanShift"
clustering_params:
  max_iter: 300

silhouette_params:
  metric: "euclidean"

embedding_path: "embeddings/ce_iam_cut20k.pt"

plot_output_path: "plots/ce_iam_kmeans.png"
debug: false
