model: encoder
checkpoint_path: checkpoints/cross_entropy.ckpt
model_config_path: configs/encoder_crossentropy/encoder_config_crossentropy.yaml

dataset:
  type: "synthetic"
  root_path: data/fonts
  fonts_test: fonts_test_cut.json
  words_test: words_test.json

dataloader:
  batch_size: 128
  num_workers: 8

# Correct: 392
cluster:
  min_samples: 350
  max_samples: 450
  step: 10

umap:
  n_neighbors: 30
  min_dist: 0.0
  n_components: 32
  random_state: 129

clustering_method: "AgglomerativeClustering"
clustering_params:
  metric: "euclidean"

silhouette_params:
  metric: "euclidean"

embedding_path: "embeddings/ce_synt.pt"

plot_output_path: "plots/ce_synt_agglr.png"
debug: false
