model: encoder
checkpoint_path: checkpoints/cross_entropy.ckpt
model_config_path: configs/encoder_crossentropy/encoder_config_crossentropy.yaml

dataset:
  type: "syntetic"
  root_path: data/fonts

dataloader:
  batch_size: 128
  num_workers: 8

cluster:
  min_samples: 2
  max_samples: 50
  step: 1

umap:
  n_neighbors: 30
  min_dist: 0.0
  n_components: 32
  random_state: 129

clustering_method: "AgglomerativeClustering"
clustering_params:
  metric: "euclidean"

silhouette_params:
  metric: "euclidean"

embedding_path: "embeddings/ce_synt.pt"

plot_output_path: "plots/ce_synt_agglr.png"
debug: false
