dataset:
  type: "cvl_resized"
  root_path: data/cvl_resized
  cut: 20000

dataloader:
  batch_size: 128
  num_workers: 8

# Correct number: 53
cluster:
  correct: 53
  min_samples: 20
  max_samples: 120
  step: 10

umap:
  n_neighbors: 120
  min_dist: 0.0
  n_components: 10
  random_state: 42
  metric: "cosine"

clustering_method: "AgglomerativeClustering"
clustering_params:
  linkage: "average"
  metric: "cosine"

silhouette_params:
  metric: "cosine"

embedding_path: "embeddings/"

plot_output_path: "plots/"
debug: false
