model: encoder
checkpoint_path: checkpoints/arcface.ckpt
model_config_path: configs/encoder_arcface/encoder_config_arcface.yaml

dataset:
  type: "synthetic"
  root_path: data/fonts
  fonts_test: fonts_test_cut.json
  words_test: words_test.json

dataloader:
  batch_size: 128
  num_workers: 8

# Correct: 392
cluster:
  min_samples: 350
  max_samples: 450
  step: 10

umap:
  n_neighbors: 30
  min_dist: 0.0
  n_components: 32
  random_state: 129
  metric: "cosine"

clustering_method: "AgglomerativeClustering"
clustering_params:
  linkage: "average"
  metric: "cosine"

silhouette_params:
  metric: "cosine"

embedding_path: "embeddings/arcface_synt.pt"

plot_output_path: "plots/arcface_synt_agglr.png"
debug: false
