model: encoder
checkpoint_path: checkpoints/cross_entropy.ckpt
model_config_path: configs/encoder_crossentropy/encoder_config_crossentropy_old.yaml

dataset:
  type: "cvl_resized"
  root_path: data/cvl_resized
  cut: 20000

dataloader:
  batch_size: 128
  num_workers: 8

# Correct number: 53
cluster:
  correct: 53
  min_samples: 10
  max_samples: 350
  step: 10

umap:
  n_neighbors: 30
  min_dist: 0.0
  n_components: 32
  random_state: 129

clustering_method: "KMeans"
clustering_params:
  n_init: 10
  max_iter: 300

silhouette_params:
  metric: "euclidean"

embedding_path: "embeddings/ce_cvl_cut20k.pt"

plot_output_path: "plots/ce_cvl_kmeans.png"
debug: false
