model_name: encoder
checkpoint_path: ~

dataset:
  type: iam_resized
  root_path: data/iam_resized
  
dataloader:
  batch_size: 128
  num_workers: 48

model:
  backbone: resnet18
  criterion: cross_entropy
  number_of_classes: 672

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: ExponentialLR
  params:
    gamma: 0.999974416048

training:
  epochs: 100
  device: cuda

debug: false
logs: logs
