model: snn
checkpoint_path: checkpoints/snn.ckpt
model_config_path: configs/snn/snn_config.yaml

dataset:
  type: "synthetic"
  root_path: data/fonts
  fonts_test: fonts_test_cut.json
  words_test: words_test.json

dataloader:
  batch_size: 128
  num_workers: 8

# Correct: 83
cluster:
  correct: 83
  min_samples: 30
  max_samples: 150
  step: 10

umap:
  n_neighbors: 120
  min_dist: 0.0
  n_components: 10
  random_state: 42

clustering_method: "AgglomerativeClustering"
clustering_params:
  metric: "euclidean"

silhouette_params:
  metric: "euclidean"

embedding_path: "embeddings/"

plot_output_path: "plots/"
debug: false
