model_name: snn

dataset:
  root_path: data/fonts
  fonts_train: fonts_train_2000.json
  fonts_val: fonts_val_cut.json
  fonts_test: fonts_test_cut.json
  words_train: words_train_2000.json
  words_val: words_val.json
  words_test: words_test.json

dataloader:
  batch_size: 128
  num_workers: 48

model:
  backbone: resnet18
  alpha: 5.0

optimizer:
  name: Adam
  params:
    lr: 0.0005

training:
  epochs: 200
  device: cuda

debug: false

