model: encoder
checkpoint_path: checkpoints/cross_entropy.ckpt

dataset:
  root_path: data/fonts
  fonts_test: fonts_debug.json
  words_test: words_test.json

dataloader:
  batch_size: 128
  num_workers: 8

cluster:
  min_samples: 170
  max_samples: 250
  step: 10

umap:
  n_neighbors: 30
  min_dist: 0.0
  n_components: 25
  random_state: 42

debug: false
