model_name: encoder

dataset:
  root_path: data/v1.0
  fonts_train: fonts_train_2000.json
  fonts_val: fonts_val_cut.json
  fonts_test: fonts_test_cut.json
  words_train: words_train_2000.json
  words_val: words_val.json
  words_test: words_test.json

dataloader:
  batch_size: 128
  num_workers: 48

model:
  backbone: resnet18
  criterion: arcface
  number_of_classes: 4113

optimizer:
  name: SGD
  params:
    lr: 0.1
    momentum: 0.9

scheduler:
  name: MultiStepLR
  params:
    milestones:
      - 6
      - 9
    gamma: 0.1

training:
  epochs: 15
  device: cuda

debug: false
logs: logs
