dataset:
  root_path: data/fonts

dataloader:
  batch_size: 32
  num_workers: 8

model:
  backbone: resnet18
  number_of_classes: 10400

optimizer:
  name: Adam
  params:
    lr: 0.00002

scheduler:
  decay_factor: 0.999974416048

training:
  epochs: 1000
  device: mps

debug: true

logs: logs
