dataset:
  train_path: data/segments_train
  val_path: data/segments_val
  test_path: data/segments_test

dataloader:
  batch_size: 64
  num_workers: 8

model:
  backbone: resnet18
  alpha: 2.0

optimizer:
  name: Adam
  params:
    lr: 0.0005

training:
  epochs: 200
  device: mps

debug: false

