model: encoder
checkpoint_path: checkpoints/arcface.ckpt
model_config_path: configs/encoder_arcface/encoder_config_arcface.yaml

dataset:
  type: "cvl_resized"
  root_path: data/cvl_resized
  cut: 20000

dataloader:
  batch_size: 128
  num_workers: 8

# Correct number: 53
cluster:
  correct: 53
  min_samples: 10
  max_samples: 350
  step: 10

clustering_method: "AgglomerativeClustering"
clustering_params:
  linkage: "average"
  metric: "cosine"

silhouette_params:
  metric: "cosine"

embedding_path: "embeddings/arcface_cvl_cut20k.pt"

plot_output_path: "plots/arcface_cvl_agglr_no_umap.png"
debug: false
