model: encoder
checkpoint_path: checkpoints/arcface.ckpt
model_config_path: configs/encoder_arcface/encoder_config_arcface.yaml

dataset:
  type: "synthetic"
  root_path: data/fonts
  fonts_test: fonts_test_100.json
  words_test: words_test.json

dataloader:
  batch_size: 128
  num_workers: 8

# Correct: 100
cluster:
  correct: 100
  min_samples: 50
  max_samples: 150
  step: 10

clustering_method: "AgglomerativeClustering"
clustering_params:
  linkage: "average"
  metric: "cosine"

silhouette_params:
  metric: "cosine"

embedding_path: "embeddings/arcface_synt_100.pt"

plot_output_path: "plots/arcface_synt_agglr_no_umap.png"
debug: false
